tests/unit/test_damo_schemes_input: Fix wrong Damos constructor call
Commit 61c71da0db3e ("_damon: Add target_nid under scheme") has updated
Damos constructor to receive 'target_nid', but the calls of the function
in test_damo_schemes_input.py was not accordingly updated.  As a result,
the test fails as below:

    FAIL: test_schemes_option_to_damos (__main__.TestDamoSchemesInput.test_schemes_option_to_damos)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/sjpark/damo/./tests/unit/test_damo_schemes_input.py", line 133, in test_schemes_option_to_damos
        _test_damo_common.test_input_expects(self,
      File "/home/sjpark/damo/tests/unit/_test_damo_common.py", line 9, in test_input_expects
        testcase.assertEqual(function(input_), input_expects[input_])
    AssertionError: Lists differ: [acti[293 chars] 0 %
    filter 0
        anon matching
    filter 1
        m[141 chars]0 B)] != [acti[293 chars] 0 %
    statistics
        tried 0 times (0 B)
        ap[62 chars]0 B)]

    First differing element 0:
    actio[292 chars] 0 %
    filter 0
        anon matching
    filter 1
        m[140 chars](0 B)
    actio[292 chars] 0 %
    statistics
        tried 0 times (0 B)
        ap[61 chars](0 B)

      [action: stat per aggr interval
      target access pattern
          sz: [0 B, 0 B]
          nr_accesses: [0 samples, 0 samples]
          age: [0 aggr_intervals, 0 aggr_intervals]
      quotas
          0 ns / 0 B / 0 B per 0 ns
          priority: sz 0 %, nr_accesses 0 %, age 0 %
      watermarks
          metric none, interval 0 ns
          0 %, 0 %, 0 %
    - filter 0
    -     anon matching
    - filter 1
    -     memcg nomatching /all/latency-critical
      statistics
          tried 0 times (0 B)
          applied 0 times (0 B)
          quota exceeded 0 times
      tried regions (0 B)]

Update the calls to fix the problem.

Fixes: 61c71da0db3e ("_damon: Add target_nid under scheme")
Signed-off-by: SeongJae Park <sj@kernel.org>