_damon: Import time
This commit fixes the error due to not importint 'time', which is like
below:

    Traceback (most recent call last):
      File "./damo", line 133, in <module>
        main()
      File "./damo", line 100, in main
        damo_record.main(args)
      File "/home/sjpark/damo/damo_record.py", line 147, in main
        record_request=_damon.DamonRecord(args.rbuf, args.out))
      File "/home/sjpark/damo/_damon.py", line 406, in
    turn_implicit_args_damon_on
        return turn_damon('on', kdamonds), kdamonds
      File "/home/sjpark/damo/_damon.py", line 183, in turn_damon
        time.sleep(1)
    NameError: global name 'time' is not defined

Signed-off-by: SeongJae Park <sj38.park@gmail.com>