damo: Set import path of the directory first priority
On systems having validate module, damo fails as below:

    $ damo -h
    Traceback (most recent call last):
      File "/usr/local/bin/damo", line 8, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.6/dist-packages/damo/damo.py", line 63, in main
        validate.set_argparser(parser_validate)
    AttributeError: module 'validate' has no attribute 'set_argparser'
    $

That's because the validate module of damo is loaded later than that.
This commit fixes the issue by making damo loads modules in current path
first.

Signed-off-by: SeongJae Park <sj@kernel.org>