_paddr_layout: Fix wrong 'paddr_ranges()' invocation
Commit 5902c4b ("Support physical address DAMOS") made 'paddr_ranges()'
function call in '_paddr_layout' module incorrect, so it crashes as
below when '--numa_node' option is given.

    $ sudo ./damo record --numa_node 1 paddr
    Traceback (most recent call last):
      File "./damo", line 91, in <module>
        main()
      File "./damo", line 70, in main
        record.main(args)
      File "/home/sjpark/damo/record.py", line 157, in main
        init_regions = _paddr_layout.paddr_region_of(numa_node)
      File "/home/sjpark/damo/_paddr_layout.py", line 159, in paddr_region_of
        paddr_ranges = _paddr_layout.paddr_ranges()
    NameError: global name '_paddr_layout' is not defined

This commit fixes the wrong invocation.

Signed-off-by: SeongJae Park <sj@kernel.org>